### ISSUE TITLE
Great app!

### ISSUE THREAD

**Issue by lasergoat** [brandonhorst/slack-bible#2]
Is there any way to configure the app to link to a different version than NIV? Do you want to talk about a PR?

**Comment by brandonhorst** [comment]
The link doesn't specify a version - it just links to whatever version your default is set to on Bible Gateway (which is NIV by default, but it's ESV for me). There's no way to have "settings" in the Outgoing WebHooks configuration, so if you want to change the link, the best thing is probably to fork this repo and host it yourself. I think the default behavior is pretty good for the general case.

**Comment by lasergoat** [comment]
I see, so I could host my own fork and allow settings per token within my own hosted app. What about spitting the verse out instead of a link?

**Comment by brandonhorst** [comment]
What do you mean by "settings per token?" What method do you have for allowing Outbound WebHooks to process user configuration?

**Comment by lasergoat** [comment]
Just want to let you know we don't use that slack anymore. Thank you!
